[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_global_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_tache", DestinationColumnName = "Identifiant_technique_tache"], [SourceColumnName = "IRC_primo_affectation_tache", DestinationColumnName = "IRC_primo_affectation_tache"], [SourceColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation", DestinationColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation"], [SourceColumnName = "Libelle_EG_corbeille_Collective_d_affectation", DestinationColumnName = "Libelle_EG_corbeille_Collective_d_affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Systeme_applicatif", DestinationColumnName = "Systeme_applicatif"], [SourceColumnName = "Libelle_court_Processus_Metier", DestinationColumnName = "Libelle_court_Processus_Metier"], [SourceColumnName = "Libelle_court_Sous_processus_Metier", DestinationColumnName = "Libelle_court_Sous_processus_Metier"], [SourceColumnName = "Libelle_long_Etape_Metier", DestinationColumnName = "Libelle_long_Etape_Metier"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_Type_Tache_Metier", DestinationColumnName = "Libelle_long_Type_Tache_Metier"], [SourceColumnName = "Timestamp_creation_tache", DestinationColumnName = "Timestamp_creation_tache"], [SourceColumnName = "Timestamp_Affectation_tache", DestinationColumnName = "Timestamp_Affectation_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Timestamp_Statut_tache", DestinationColumnName = "Timestamp_Statut_tache"], [SourceColumnName = "Poids_de_la_tache", DestinationColumnName = "Poids_de_la_tache"], [SourceColumnName = "Degre_d_urgence_Tache", DestinationColumnName = "Degre_d_urgence_Tache"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Sensibilite", DestinationColumnName = "Sensibilite"], [SourceColumnName = "Identifiant_interne_Type_Objet_Gestion_Distribution", DestinationColumnName = "Identifiant_interne_Type_Objet_Gestion_Distribution"], [SourceColumnName = "Identifiant_interne_Type_Objet_Gestion_Reference", DestinationColumnName = "Identifiant_interne_Type_Objet_Gestion_Reference"], [SourceColumnName = "Identifiant_Interne_Type_Objet_Dossier", DestinationColumnName = "Identifiant_Interne_Type_Objet_Dossier"], [SourceColumnName = "Tache_en_Stock", DestinationColumnName = "Tache_en_Stock"], [SourceColumnName = "Tache_en_entree", DestinationColumnName = "Tache_en_entree"], [SourceColumnName = "Tache_en_Sortie", DestinationColumnName = "Tache_en_Sortie"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_global = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_global", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
shared dp_brc_global_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp1", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_global", ItemKind = "Table"]}[Data]
in
  TableNavigation;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_cfiab_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_tache", DestinationColumnName = "Identifiant_technique_tache"], [SourceColumnName = "Identifiant_fonctionnel_IRC_Tache", DestinationColumnName = "Identifiant_fonctionnel_IRC_Tache"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_type_tache", DestinationColumnName = "Libelle_long_type_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Chemin_arborescence_nom_EG_Affectation", DestinationColumnName = "Chemin_arborescence_nom_EG_Affectation"], [SourceColumnName = "Anonymisation", DestinationColumnName = "Anonymisation"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Date_de_creation_Tache", DestinationColumnName = "Date_de_creation_Tache"], [SourceColumnName = "Date_statut_Tache", DestinationColumnName = "Date_statut_Tache"], [SourceColumnName = "Anciennete_Tache", DestinationColumnName = "Anciennete_Tache"], [SourceColumnName = "Libelle_information_complementaire_nombre_1", DestinationColumnName = "Libelle_information_complementaire_nombre_1"], [SourceColumnName = "Valeur_information_complementaire_nombre_1", DestinationColumnName = "Valeur_information_complementaire_nombre_1"], [SourceColumnName = "Libelle_information_complementaire_nombre_2", DestinationColumnName = "Libelle_information_complementaire_nombre_2"], [SourceColumnName = "Valeur_information_complementaire_nombre_2", DestinationColumnName = "Valeur_information_complementaire_nombre_2"], [SourceColumnName = "Libelle_information_complementaire_nombre_3", DestinationColumnName = "Libelle_information_complementaire_nombre_3"], [SourceColumnName = "Valeur_information_complementaire_nombre_3", DestinationColumnName = "Valeur_information_complementaire_nombre_3"], [SourceColumnName = "Indicateur_presence_libelle_commentaire_utilisateur", DestinationColumnName = "Indicateur_presence_libelle_commentaire_utilisateur"], [SourceColumnName = "Indicateur_entreprise_protegee", DestinationColumnName = "Indicateur_entreprise_protegee"], [SourceColumnName = "Identifiant_interne_Type_Objet_Gestion_Reference", DestinationColumnName = "Identifiant_interne_Type_Objet_Gestion_Reference"], [SourceColumnName = "Identifiant_Public_Type_Objet_CTX2", DestinationColumnName = "Identifiant_Public_Type_Objet_CTX2"], [SourceColumnName = "Tache_en_Stock", DestinationColumnName = "Tache_en_Stock"], [SourceColumnName = "Tache_en_entree", DestinationColumnName = "Tache_en_entree"], [SourceColumnName = "Tache_en_Sortie", DestinationColumnName = "Tache_en_Sortie"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_cfiab = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_cfiab", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
shared dp_brc_cfiab_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp2", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_cfiab", ItemKind = "Table"]}[Data]
in
  TableNavigation;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_dsn_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_tache", DestinationColumnName = "Identifiant_technique_tache"], [SourceColumnName = "Identifiant_fonctionnel_IRC_Tache", DestinationColumnName = "Identifiant_fonctionnel_IRC_Tache"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_type_tache", DestinationColumnName = "Libelle_long_type_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Chemin_arborescence_nom_EG_Affectation", DestinationColumnName = "Chemin_arborescence_nom_EG_Affectation"], [SourceColumnName = "Anonymisation", DestinationColumnName = "Anonymisation"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Date_de_creation_Tache", DestinationColumnName = "Date_de_creation_Tache"], [SourceColumnName = "Date_statut_Tache", DestinationColumnName = "Date_statut_Tache"], [SourceColumnName = "Libelle_information_1", DestinationColumnName = "Libelle_information_1"], [SourceColumnName = "Libelle_information_2", DestinationColumnName = "Libelle_information_2"], [SourceColumnName = "Libelle_information_3", DestinationColumnName = "Libelle_information_3"], [SourceColumnName = "Libelle_information_complementaire_nombre_1", DestinationColumnName = "Libelle_information_complementaire_nombre_1"], [SourceColumnName = "Valeur_information_complementaire_nombre_1", DestinationColumnName = "Valeur_information_complementaire_nombre_1"], [SourceColumnName = "Libelle_information_complementaire_nombre_2", DestinationColumnName = "Libelle_information_complementaire_nombre_2"], [SourceColumnName = "Valeur_information_complementaire_nombre_2", DestinationColumnName = "Valeur_information_complementaire_nombre_2"], [SourceColumnName = "Libelle_information_complementaire_date_1", DestinationColumnName = "Libelle_information_complementaire_date_1"], [SourceColumnName = "Valeur_information_complementaire_date_1", DestinationColumnName = "Valeur_information_complementaire_date_1"], [SourceColumnName = "Indicateur_presence_libelle_commentaire_utilisateur", DestinationColumnName = "Indicateur_presence_libelle_commentaire_utilisateur"], [SourceColumnName = "SIREN", DestinationColumnName = "SIREN"], [SourceColumnName = "Indicateur_Grande_entreprise", DestinationColumnName = "Indicateur_Grande_entreprise"], [SourceColumnName = "Nombre_d_adhesions_ouvertes", DestinationColumnName = "Nombre_d_adhesions_ouvertes"], [SourceColumnName = "Indicateur_entreprise_protegee", DestinationColumnName = "Indicateur_entreprise_protegee"], [SourceColumnName = "Nombre_d_individus_moyen_d_un_identifiant_externe_entreprise_pour_un_exercice", DestinationColumnName = "Nombre_d_individus_moyen_d_un_identifiant_externe_entreprise_pour_un_exercice"], [SourceColumnName = "Nombre_de_periodes_consolidees_en_anomalie_pour_une_entreprise_et_pour_un_exercice", DestinationColumnName = "Nombre_de_periodes_consolidees_en_anomalie_pour_une_entreprise_et_pour_un_exercice"], [SourceColumnName = "Montant_des_cotisations_declares_de_l_entreprise_pour_un_exercice", DestinationColumnName = "Montant_des_cotisations_declares_de_l_entreprise_pour_un_exercice"], [SourceColumnName = "Tache_en_stock", DestinationColumnName = "Tache_en_stock"], [SourceColumnName = "Tache_en_entree", DestinationColumnName = "Tache_en_entree"], [SourceColumnName = "Tache_en_sortie", DestinationColumnName = "Tache_en_sortie"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_dsn = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_dsn", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_scl_tache_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_de_la_tache", DestinationColumnName = "Identifiant_technique_de_la_tache"], [SourceColumnName = "GPS_CICAS", DestinationColumnName = "GPS_CICAS"], [SourceColumnName = "Libelle_EG_corbeille_Collective", DestinationColumnName = "Libelle_EG_corbeille_Collective"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Libelle_long_Type_Tache_Metier", DestinationColumnName = "Libelle_long_Type_Tache_Metier"], [SourceColumnName = "Timestamp_creation_tache", DestinationColumnName = "Timestamp_creation_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Timestamp_statut_tache", DestinationColumnName = "Timestamp_statut_tache"], [SourceColumnName = "Poids_de_la_tache", DestinationColumnName = "Poids_de_la_tache"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Sensibilite", DestinationColumnName = "Sensibilite"], [SourceColumnName = "Identifiant_du_dossier", DestinationColumnName = "Identifiant_du_dossier"], [SourceColumnName = "Libelle_IRC_paiement", DestinationColumnName = "Libelle_IRC_paiement"], [SourceColumnName = "Libelle_court_Sous_processus_metier", DestinationColumnName = "Libelle_court_Sous_processus_metier"], [SourceColumnName = "Libelle_Type_Droit", DestinationColumnName = "Libelle_Type_Droit"], [SourceColumnName = "Libelle_Type_Stock_Dossier", DestinationColumnName = "Libelle_Type_Stock_Dossier"], [SourceColumnName = "Libelle_Couleur_Dossier", DestinationColumnName = "Libelle_Couleur_Dossier"], [SourceColumnName = "Date_RDV_Dossier", DestinationColumnName = "Date_RDV_Dossier"], [SourceColumnName = "Date_d_effet_retenue_du_dossier", DestinationColumnName = "Date_d_effet_retenue_du_dossier"], [SourceColumnName = "Date_paiement_provisoire", DestinationColumnName = "Date_paiement_provisoire"], [SourceColumnName = "Type_depot", DestinationColumnName = "Type_depot"], [SourceColumnName = "Perimetre", DestinationColumnName = "Perimetre"], [SourceColumnName = "Date_limite_COM", DestinationColumnName = "Date_limite_COM"], [SourceColumnName = "Date_limite_COM_apres_provisoire", DestinationColumnName = "Date_limite_COM_apres_provisoire"], [SourceColumnName = "IRC_primo_affectation", DestinationColumnName = "IRC_primo_affectation"], [SourceColumnName = "BriqueSysteme_applicatif", DestinationColumnName = "BriqueSysteme_applicatif"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_scl_tache = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_scl_tache", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_scl_dossier_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_du_dossier", DestinationColumnName = "Identifiant_du_dossier"], [SourceColumnName = "Libelle_GPS_paiement", DestinationColumnName = "Libelle_GPS_paiement"], [SourceColumnName = "Libelle_IRC_paiement", DestinationColumnName = "Libelle_IRC_paiement"], [SourceColumnName = "Date_effet_retenue", DestinationColumnName = "Date_effet_retenue"], [SourceColumnName = "Libelle_Motif_Retraite", DestinationColumnName = "Libelle_Motif_Retraite"], [SourceColumnName = "Type_depot", DestinationColumnName = "Type_depot"], [SourceColumnName = "Libelle_Canal_Origine", DestinationColumnName = "Libelle_Canal_Origine"], [SourceColumnName = "Libelle_lieu_Residence", DestinationColumnName = "Libelle_lieu_Residence"], [SourceColumnName = "Libelle_Type_Droit", DestinationColumnName = "Libelle_Type_Droit"], [SourceColumnName = "Libelle_Type_Retraite", DestinationColumnName = "Libelle_Type_Retraite"], [SourceColumnName = "Libelle_Perimetre", DestinationColumnName = "Libelle_Perimetre"], [SourceColumnName = "Derniere_Colorisation_du_dossier", DestinationColumnName = "Derniere_Colorisation_du_dossier"], [SourceColumnName = "Timestamp_reception_notification_CNAV_MSA_RSI", DestinationColumnName = "Timestamp_reception_notification_CNAV_MSA_RSI"], [SourceColumnName = "Date_reception_DLR", DestinationColumnName = "Date_reception_DLR"], [SourceColumnName = "Date_reception_preuve_etat_civil", DestinationColumnName = "Date_reception_preuve_etat_civil"], [SourceColumnName = "Date_reception_RIB", DestinationColumnName = "Date_reception_RIB"], [SourceColumnName = "Timestamp_evenement_Demande_de_paiement_provisoire", DestinationColumnName = "Timestamp_evenement_Demande_de_paiement_provisoire"], [SourceColumnName = "Timestamp_evenement_de_mise_en_paiement_provisoire", DestinationColumnName = "Timestamp_evenement_de_mise_en_paiement_provisoire"], [SourceColumnName = "Timestamp_evenement_Demande_de_paiement_definitif", DestinationColumnName = "Timestamp_evenement_Demande_de_paiement_definitif"], [SourceColumnName = "Nombre_de_points_inscrits", DestinationColumnName = "Nombre_de_points_inscrits"], [SourceColumnName = "Corbeille_individuelle_derniere_tache_Constitution", DestinationColumnName = "Corbeille_individuelle_derniere_tache_Constitution"], [SourceColumnName = "Libelle_Chemin_Arborescence_derniere_tache_Constitution", DestinationColumnName = "Libelle_Chemin_Arborescence_derniere_tache_Constitution"], [SourceColumnName = "Date_limite_COM", DestinationColumnName = "Date_limite_COM"], [SourceColumnName = "Date_limite_COM_apres_provisoire", DestinationColumnName = "Date_limite_COM_apres_provisoire"], [SourceColumnName = "Presence_dossier_IRCANTEC", DestinationColumnName = "Presence_dossier_IRCANTEC"], [SourceColumnName = "Libelle_long_motif_couleur_Carriere", DestinationColumnName = "Libelle_long_motif_couleur_Carriere"], [SourceColumnName = "Libelle_long_motif_couleur_Calcul_Droits", DestinationColumnName = "Libelle_long_motif_couleur_Calcul_Droits"], [SourceColumnName = "Libelle_long_motif_couleur_Synthese_Individu", DestinationColumnName = "Libelle_long_motif_couleur_Synthese_Individu"], [SourceColumnName = "Libelle_long_motif_couleur_Demande_de_retraite", DestinationColumnName = "Libelle_long_motif_couleur_Demande_de_retraite"], [SourceColumnName = "Motif_colorisation_onglet_Famille", DestinationColumnName = "Motif_colorisation_onglet_Famille"], [SourceColumnName = "Nombre_de_pieces_a_traiter", DestinationColumnName = "Nombre_de_pieces_a_traiter"], [SourceColumnName = "Presence_tache_en_cours", DestinationColumnName = "Presence_tache_en_cours"], [SourceColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation", DestinationColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation"], [SourceColumnName = "Libelle_EG_corbeille_Collective_d_affectation", DestinationColumnName = "Libelle_EG_corbeille_Collective_d_affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Complexite_carriere", DestinationColumnName = "Complexite_carriere"], [SourceColumnName = "Nombre_de_preuves_en_attente", DestinationColumnName = "Nombre_de_preuves_en_attente"], [SourceColumnName = "Timestamp_Envoi_Courrier_PMR", DestinationColumnName = "Timestamp_Envoi_Courrier_PMR"], [SourceColumnName = "Identifiant_individu_de_Communication", DestinationColumnName = "Identifiant_individu_de_Communication"], [SourceColumnName = "Flag_Stock_non_paye", DestinationColumnName = "Flag_Stock_non_paye"], [SourceColumnName = "Flag_Stock_provisoire", DestinationColumnName = "Flag_Stock_provisoire"], [SourceColumnName = "Date_CER_Integral", DestinationColumnName = "Date_CER_Integral"], [SourceColumnName = "Code_Liquidation_Tous_Regime", DestinationColumnName = "Code_Liquidation_Tous_Regime"], [SourceColumnName = "Libelle_Statut_PSAA", DestinationColumnName = "Libelle_Statut_PSAA"], [SourceColumnName = "Corbeille_individuelle_derniere_tache_Etude", DestinationColumnName = "Corbeille_individuelle_derniere_tache_Etude"], [SourceColumnName = "Libelle_Chemin_Arborescence_derniere_tache_Etudes", DestinationColumnName = "Libelle_Chemin_Arborescence_derniere_tache_Etudes"], [SourceColumnName = "Statut_Tache_Dossier", DestinationColumnName = "Statut_Tache_Dossier"], [SourceColumnName = "Type_Tache_Dossier", DestinationColumnName = "Type_Tache_Dossier"], [SourceColumnName = "Affectation_Dossier", DestinationColumnName = "Affectation_Dossier"], [SourceColumnName = "Indicateur_Pieces_a_traiter", DestinationColumnName = "Indicateur_Pieces_a_traiter"], [SourceColumnName = "Indicateur_Absence_de_tache", DestinationColumnName = "Indicateur_Absence_de_tache"], [SourceColumnName = "Indicateur_NPV_recue", DestinationColumnName = "Indicateur_NPV_recue"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_scl_dossier = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_scl_dossier", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_cfiab_stock_tache_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_tache", DestinationColumnName = "Identifiant_technique_tache"], [SourceColumnName = "Identifiant_fonctionnel_IRC_Tache", DestinationColumnName = "Identifiant_fonctionnel_IRC_Tache"], [SourceColumnName = "Systeme_applicatif", DestinationColumnName = "Systeme_applicatif"], [SourceColumnName = "Libelle_court_Processus_Metier", DestinationColumnName = "Libelle_court_Processus_Metier"], [SourceColumnName = "Libelle_court_Sous_processus_Metier", DestinationColumnName = "Libelle_court_Sous_processus_Metier"], [SourceColumnName = "Libelle_long_Etape_Metier", DestinationColumnName = "Libelle_long_Etape_Metier"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_type_tache", DestinationColumnName = "Libelle_long_type_tache"], [SourceColumnName = "Timestamp_creation_tache", DestinationColumnName = "Timestamp_creation_tache"], [SourceColumnName = "Timestamp_Affectation_tache", DestinationColumnName = "Timestamp_Affectation_tache"], [SourceColumnName = "Timestamp_Statut_tache", DestinationColumnName = "Timestamp_Statut_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Chemin_arborescence_nom_EG_Affectation", DestinationColumnName = "Chemin_arborescence_nom_EG_Affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Anciennete_Tache", DestinationColumnName = "Anciennete_Tache"], [SourceColumnName = "Libelle_information_complementaire_nombre_1", DestinationColumnName = "Libelle_information_complementaire_nombre_1"], [SourceColumnName = "Valeur_information_complementaire_nombre_1", DestinationColumnName = "Valeur_information_complementaire_nombre_1"], [SourceColumnName = "Libelle_information_complementaire_nombre_2", DestinationColumnName = "Libelle_information_complementaire_nombre_2"], [SourceColumnName = "Valeur_information_complementaire_nombre_2", DestinationColumnName = "Valeur_information_complementaire_nombre_2"], [SourceColumnName = "Libelle_information_complementaire_nombre_3", DestinationColumnName = "Libelle_information_complementaire_nombre_3"], [SourceColumnName = "Valeur_information_complementaire_nombre_3", DestinationColumnName = "Valeur_information_complementaire_nombre_3"], [SourceColumnName = "Indicateur_entreprise_protegee", DestinationColumnName = "Indicateur_entreprise_protegee"], [SourceColumnName = "Identifiant_Public_Type_Objet_CTX2", DestinationColumnName = "Identifiant_Public_Type_Objet_CTX2"], [SourceColumnName = "Identifiant_Interne_Type_Objet_Dossier", DestinationColumnName = "Identifiant_Interne_Type_Objet_Dossier"], [SourceColumnName = "Poids_de_la_tache", DestinationColumnName = "Poids_de_la_tache"], [SourceColumnName = "Degre_d_urgence_Tache", DestinationColumnName = "Degre_d_urgence_Tache"], [SourceColumnName = "Sensibilite", DestinationColumnName = "Sensibilite"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_cfiab_stock_tache = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_cfiab_stock_tache", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_dsn_stock_tache_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_technique_tache", DestinationColumnName = "Identifiant_technique_tache"], [SourceColumnName = "Identifiant_fonctionnel_IRC_Tache", DestinationColumnName = "Identifiant_fonctionnel_IRC_Tache"], [SourceColumnName = "Systeme_applicatif", DestinationColumnName = "Systeme_applicatif"], [SourceColumnName = "Libelle_court_Processus_Metier", DestinationColumnName = "Libelle_court_Processus_Metier"], [SourceColumnName = "Libelle_court_Sous_processus_Metier", DestinationColumnName = "Libelle_court_Sous_processus_Metier"], [SourceColumnName = "Libelle_long_Etape_Metier", DestinationColumnName = "Libelle_long_Etape_Metier"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_type_tache", DestinationColumnName = "Libelle_long_type_tache"], [SourceColumnName = "Timestamp_creation_tache", DestinationColumnName = "Timestamp_creation_tache"], [SourceColumnName = "Timestamp_Affectation_tache", DestinationColumnName = "Timestamp_Affectation_tache"], [SourceColumnName = "Timestamp_Statut_tache", DestinationColumnName = "Timestamp_Statut_tache"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "Chemin_arborescence_nom_EG_Affectation", DestinationColumnName = "Chemin_arborescence_nom_EG_Affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Date_limite_de_traitement", DestinationColumnName = "Date_limite_de_traitement"], [SourceColumnName = "Libelle_information_1", DestinationColumnName = "Libelle_information_1"], [SourceColumnName = "Libelle_information_2", DestinationColumnName = "Libelle_information_2"], [SourceColumnName = "Libelle_information_3", DestinationColumnName = "Libelle_information_3"], [SourceColumnName = "Libelle_information_complementaire_nombre_1", DestinationColumnName = "Libelle_information_complementaire_nombre_1"], [SourceColumnName = "Valeur_information_complementaire_nombre_1", DestinationColumnName = "Valeur_information_complementaire_nombre_1"], [SourceColumnName = "Libelle_information_complementaire_nombre_2", DestinationColumnName = "Libelle_information_complementaire_nombre_2"], [SourceColumnName = "Valeur_information_complementaire_nombre_2", DestinationColumnName = "Valeur_information_complementaire_nombre_2"], [SourceColumnName = "Libelle_information_complementaire_date_1", DestinationColumnName = "Libelle_information_complementaire_date_1"], [SourceColumnName = "Valeur_information_complementaire_date_1", DestinationColumnName = "Valeur_information_complementaire_date_1"], [SourceColumnName = "SIREN", DestinationColumnName = "SIREN"], [SourceColumnName = "Indicateur_Grande_entreprise", DestinationColumnName = "Indicateur_Grande_entreprise"], [SourceColumnName = "Nombre_d_adhesions_ouvertes", DestinationColumnName = "Nombre_d_adhesions_ouvertes"], [SourceColumnName = "Indicateur_entreprise_protegee", DestinationColumnName = "Indicateur_entreprise_protegee"], [SourceColumnName = "Nombre_d_individus_moyen_d_un_identifiant_externe_entreprise_pour_un_exercice", DestinationColumnName = "Nombre_d_individus_moyen_d_un_identifiant_externe_entreprise_pour_un_exercice"], [SourceColumnName = "Nombre_de_periodes_consolidees_en_anomalie_pour_une_entreprise_et_pour_un_exercice", DestinationColumnName = "Nombre_de_periodes_consolidees_en_anomalie_pour_une_entreprise_et_pour_un_exercice"], [SourceColumnName = "Montant_des_cotisations_declares_de_l_entreprise_pour_un_exercice", DestinationColumnName = "Montant_des_cotisations_declares_de_l_entreprise_pour_un_exercice"], [SourceColumnName = "Poids_de_la_tache", DestinationColumnName = "Poids_de_la_tache"], [SourceColumnName = "Degre_d_urgence_Tache", DestinationColumnName = "Degre_d_urgence_Tache"], [SourceColumnName = "Sensibilite", DestinationColumnName = "Sensibilite"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_dsn_stock_tache = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_dsn_stock_tache", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_scl_dossier_stock_synthese_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "Identifiant_du_dossier", DestinationColumnName = "Identifiant_du_dossier"], [SourceColumnName = "Identifiant_individu_de_Communication", DestinationColumnName = "Identifiant_individu_de_Communication"], [SourceColumnName = "Libelle_GPS_paiement", DestinationColumnName = "Libelle_GPS_paiement"], [SourceColumnName = "Libelle_IRC_paiement", DestinationColumnName = "Libelle_IRC_paiement"], [SourceColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation", DestinationColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Date_effet_retenue", DestinationColumnName = "Date_effet_retenue"], [SourceColumnName = "Libelle_Motif_Retraite", DestinationColumnName = "Libelle_Motif_Retraite"], [SourceColumnName = "Type_depot", DestinationColumnName = "Type_depot"], [SourceColumnName = "Libelle_Canal_Origine", DestinationColumnName = "Libelle_Canal_Origine"], [SourceColumnName = "Libelle_lieu_Residence", DestinationColumnName = "Libelle_lieu_Residence"], [SourceColumnName = "Libelle_Type_Droit", DestinationColumnName = "Libelle_Type_Droit"], [SourceColumnName = "Libelle_Type_Retraite", DestinationColumnName = "Libelle_Type_Retraite"], [SourceColumnName = "Derniere_Colorisation_du_dossier", DestinationColumnName = "Derniere_Colorisation_du_dossier"], [SourceColumnName = "Libelle_long_motif_couleur_Carriere", DestinationColumnName = "Libelle_long_motif_couleur_Carriere"], [SourceColumnName = "Libelle_long_motif_couleur_Calcul_Droits", DestinationColumnName = "Libelle_long_motif_couleur_Calcul_Droits"], [SourceColumnName = "Libelle_long_motif_couleur_Synthese_Individu", DestinationColumnName = "Libelle_long_motif_couleur_Synthese_Individu"], [SourceColumnName = "Libelle_long_motif_couleur_Demande_de_retraite", DestinationColumnName = "Libelle_long_motif_couleur_Demande_de_retraite"], [SourceColumnName = "Motif_colorisation_onglet_Famille", DestinationColumnName = "Motif_colorisation_onglet_Famille"], [SourceColumnName = "Timestamp_reception_notification_CNAV_MSA_RSI", DestinationColumnName = "Timestamp_reception_notification_CNAV_MSA_RSI"], [SourceColumnName = "Date_reception_DLR", DestinationColumnName = "Date_reception_DLR"], [SourceColumnName = "Date_reception_preuve_etat_civil", DestinationColumnName = "Date_reception_preuve_etat_civil"], [SourceColumnName = "Date_reception_RIB", DestinationColumnName = "Date_reception_RIB"], [SourceColumnName = "Timestamp_evenement_Demande_de_paiement_provisoire", DestinationColumnName = "Timestamp_evenement_Demande_de_paiement_provisoire"], [SourceColumnName = "Timestamp_evenement_de_mise_en_paiement_provisoire", DestinationColumnName = "Timestamp_evenement_de_mise_en_paiement_provisoire"], [SourceColumnName = "Timestamp_evenement_Demande_de_paiement_definitif", DestinationColumnName = "Timestamp_evenement_Demande_de_paiement_definitif"], [SourceColumnName = "Nombre_de_points_inscrits", DestinationColumnName = "Nombre_de_points_inscrits"], [SourceColumnName = "Presence_dossier_IRCANTEC", DestinationColumnName = "Presence_dossier_IRCANTEC"], [SourceColumnName = "Nombre_de_pieces_a_traiter", DestinationColumnName = "Nombre_de_pieces_a_traiter"], [SourceColumnName = "Nombre_tache_en_stock", DestinationColumnName = "Nombre_tache_en_stock"], [SourceColumnName = "Complexite_carriere", DestinationColumnName = "Complexite_carriere"], [SourceColumnName = "Nombre_de_preuves_en_attente", DestinationColumnName = "Nombre_de_preuves_en_attente"], [SourceColumnName = "Flag_Stock_non_paye", DestinationColumnName = "Flag_Stock_non_paye"], [SourceColumnName = "Flag_Stock_provisoire", DestinationColumnName = "Flag_Stock_provisoire"], [SourceColumnName = "Indicateur_Pieces_a_traiter", DestinationColumnName = "Indicateur_Pieces_a_traiter"], [SourceColumnName = "Indicateur_NPV_recue", DestinationColumnName = "Indicateur_NPV_recue"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_scl_dossier_stock_synthese = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_scl_dossier_stock_synthese", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dp_brc_agrege_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "Numero_Semaine", DestinationColumnName = "Numero_Semaine"], [SourceColumnName = "Code_GPS", DestinationColumnName = "Code_GPS"], [SourceColumnName = "IRC_primo_affectation_tache", DestinationColumnName = "IRC_primo_affectation_tache"], [SourceColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation", DestinationColumnName = "Libelle_Chemin_Arborescence_nom_de_l_entite_de_Gestion_d_affectation"], [SourceColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache", DestinationColumnName = "Corbeille_Dernier_Identifiant_Utilisateur_RCI_rattache"], [SourceColumnName = "Systeme_applicatif", DestinationColumnName = "Systeme_applicatif"], [SourceColumnName = "Libelle_court_Processus_Metier", DestinationColumnName = "Libelle_court_Processus_Metier"], [SourceColumnName = "Libelle_court_Sous_processus_Metier", DestinationColumnName = "Libelle_court_Sous_processus_Metier"], [SourceColumnName = "Libelle_long_Etape_Metier", DestinationColumnName = "Libelle_long_Etape_Metier"], [SourceColumnName = "Code_type_tache", DestinationColumnName = "Code_type_tache"], [SourceColumnName = "Libelle_long_Type_Tache_Metier", DestinationColumnName = "Libelle_long_Type_Tache_Metier"], [SourceColumnName = "Libelle_long_Statut_Tache", DestinationColumnName = "Libelle_long_Statut_Tache"], [SourceColumnName = "NB_TACHE_STOCK", DestinationColumnName = "NB_TACHE_STOCK"], [SourceColumnName = "NB_TACHE_ENTREE", DestinationColumnName = "NB_TACHE_ENTREE"], [SourceColumnName = "NB_TACHE_SORTIE", DestinationColumnName = "NB_TACHE_SORTIE"], [SourceColumnName = "CurrentUTC", DestinationColumnName = "integration_ts"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dp_brc_agrege = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "8525f6de-ac22-4dcd-81ca-31d4b406a6aa"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dp_brc_agrege", ItemKind = "Table"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 2", {"integration_ts"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns", "CurrentUTC", each DateTimeZone.UtcNow()), {{"CurrentUTC", type datetime}})
in
  #"Added custom";
shared dp_brc_dsn_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp3", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_dsn", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_scl_tache_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp4", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_scl_tache", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_scl_dossier_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp5", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_scl_dossier", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_brc_cfiab_stock_tache_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp6", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_cfiab_stock_tache", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_brc_dsn_stock_tache_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp7", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_dsn_stock_tache", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_scl_dossier_stock_synthese_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp8", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_scl_dossier_stock_synthese", ItemKind = "Table"]}[Data]
in
  TableNavigation;
shared dp_brc_agrege_DataDestination = let
  Pattern = Lakehouse.Contents([HierarchicalNavigation = true, CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d500bac7-7518-4386-b1f8-857ca400e400"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "05a7438c-de65-493f-9ab4-a14c2617a07b"]}[Data],
  Navigation_3 = Navigation_2{[Id = "dp9", ItemKind = "Schema"]}[Data],
  TableNavigation = Navigation_3{[Id = "dp_brc_agrege", ItemKind = "Table"]}[Data]
in
  TableNavigation;
